"""Add priority to Plan

Revision ID: d1caff634799
Revises: 
Create Date: 2026-05-17 00:03:25.966517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1caff634799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'priority',
                sa.String(length=20),
                nullable=False,
                server_default='normal'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###